version: "3.9"

services:
  db:
    image: mariadb:11
    container_name: nrl-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pass   # velg noe, men husk det
      MYSQL_DATABASE: nrl
      MYSQL_USER: nrl_user
      MYSQL_PASSWORD: nrl_pass
    ports:
      - "3307:3306"   # host:container
    volumes:
      - nrl-db:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d:ro

  nrlapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nrlapp
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      # Connection string INNE I CONTAINEREN (db = service-navn)
      ConnectionStrings__DefaultConnection: "Server=db;Port=3306;Database=nrl;User Id=nrl_user;Password=nrl_pass;SslMode=none;TreatTinyAsBoolean=true;CharSet=utf8mb4"
    ports:
      - "8080:8080"   # åpne appen på http://localhost:8080

volumes:
  nrl-db:

